### ISSUE TITLE
[FEAT] 회원가입 구현 

### ISSUE THREAD

**Issue by fullgukbap** [he-he-heng/toktok-backend#1]
## 어떤 기능입니까?
User의 회원가입 기능을 구현합니다.

## TODO
- [x] 데이터베이스 모델링 
- [x] User Domain 정의
- [x] .env 파일 작성
- [x] Config 파일 설정
- [x] Database Connection 처리

## 데드라인
2024/06/18:21:00 ~ 2024/06/19:14:00

## 기타 사항
내용 없음
